version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: yuk2/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/var/www/foodgram/media/

  frontend:
    container_name: foodgram-front
    image: yuk2/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - media:/media

  nginx:
    container_name: foodgram-proxy
    image: yuk2/foodgram_gateway
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles
      - media:/var/www/foodgram/media/
    depends_on:
      - backend