server {

    listen 80;
    client_max_body_size 20M;

    location /s/ {
        proxy_pass http://backend:8000$request_uri;
        proxy_set_header Host $host;
    }

    location /media/ {
        alias /var/www/foodgram/media/;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $http_host;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $http_host;
    }

    location /api/docs/ {
        alias /docs/;
        index redoc.html;
    }

    location / {
        alias /staticfiles/;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
