# Generated by Django 5.2.5 on 2025-08-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение готового блюда', upload_to='recipes/images/', verbose_name='Изображение'),
        ),
    ]
